# 1. Definición de la Aplicación
applications:
  app:
    type: "python:3.12" # Asegúrate de que 3.13 ya esté soportado en tu región de Upsun
    source:
      root: "/"

    relationships:
      database: "db:postgresql"

    mounts:
      'static':
        source: local
        source_path: static

    web:
      upstream:
        socket_family: unix
      commands:
        start: gunicorn -w 4 -b unix:$SOCKET blog.wsgi:application
      locations:
        "/":
          passthru: true
        "/static":
          root: "static"
          expires: 1h
          allow: true

    hooks:
      build: |
        set -ex
        pip install --upgrade pip
        pip install -r requirements.txt
        python manage.py collectstatic --noinput
      deploy: |
        set -ex
        python manage.py migrate

# 2. Definición de Servicios
services:
  db:
    type: postgresql:15

# 3. Definición de Rutas
routes:
  "https://{default}/":
    type: upstream
    upstream: "app:http"

  "https://www.{default}/":
    type: redirect
    to: "https://{default}/"